allow mutliple listeners & auth
sleighzy/ansible-kafka pull request #13
Opened 2021-06-25 13:43 UTC by emoruzzi

2021-06-28 22:20 UTC, sleighzy commented
Hi @emoruzzi . Thanks for the contribution, much appreciated. Sorry about the delay on this, I'm currently on vacation. Will run through this in greater detail when I return and get back to with any feedback or merge. Thanks.

2021-07-15 09:03 UTC, sleighzy requested changes
Looking good, couple of minor changes.

2021-07-15 09:03 UTC, sleighzy commented on defaults/main.yaml
> +kafka_listener:
Rename to `kafka_listeners` as this is a list.

2021-07-15 09:03 UTC, sleighzy commented on templates/server.properties.j2
> +  {% for user in type.users %}
Can indent this as is nested loop.

2021-07-15 09:03 UTC, sleighzy commented on defaults/main.yaml
> +# kafka_auth_listener:
Can you flip the order of this so that it is `kafka_listener_auth`

2021-07-20 18:22 UTC, emoruzzi commented on defaults/main.yaml
> +kafka_listener:
updated

2021-07-20 18:22 UTC, emoruzzi commented on templates/server.properties.j2
> +  {% for user in type.users %}
updated

2021-07-20 18:22 UTC, emoruzzi commented on defaults/main.yaml
> +# kafka_auth_listener:
updated here and other places

2021-07-21 08:23 UTC, sleighzy requested changes
Just needs the update to `kafka_listeners` and then should be good to go.

2021-07-21 08:23 UTC, sleighzy commented on templates/server.properties.j2
> +listeners={{ kafka_listener | join(",")}}
`kafka_listener` -> `kafka_listeners`

2021-08-05 08:00 UTC, sleighzy commented
Hi @emoruzzi . Are you able to make the outstanding change to have this PR completed? Would be good to see this as part of the role so I am appreciating your efforts.

2021-08-05 14:25 UTC, emoruzzi commented on templates/server.properties.j2
> +listeners={{ kafka_listener | join(",")}}
updated

2021-08-05 14:26 UTC, emoruzzi commented
Fixed the issues - sorry didn't get the last email. Thanks for checking back in.

2021-08-27 20:38 UTC, sleighzy approved these changes

2021-08-27 20:39 UTC, merged